//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from STEP.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace STEP {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class STEPParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, Digit=13, Digits=14, Letter=15, CapitalLetter=16, 
		DateTime=17, Derived=18, EnumBoolLogical=19, ENDSEC=20, FILE_DESCRIPTION=21, 
		FILE_NAME=22, FILE_SCHEMA=23, HEADER=24, Id=25, ISO=26, ISO_END=27, StringLiteral=28, 
		TypeRef=29, Undefined=30, NewlineChar=31, WS=32, Comments=33;
	public const int
		RULE_author = 0, RULE_authorisation = 1, RULE_collection = 2, RULE_collectionValue = 3, 
		RULE_constructor = 4, RULE_data = 5, RULE_description = 6, RULE_file = 7, 
		RULE_fileDescription = 8, RULE_fileName = 9, RULE_filePath = 10, RULE_fileSchema = 11, 
		RULE_header = 12, RULE_implementation = 13, RULE_instance = 14, RULE_name = 15, 
		RULE_originating_system = 16, RULE_organization = 17, RULE_parameter = 18, 
		RULE_preprocessor_version = 19, RULE_timeStamp = 20, RULE_value = 21, 
		RULE_viewDefinition = 22, RULE_viewDefinitionType = 23;
	public static readonly string[] ruleNames = {
		"author", "authorisation", "collection", "collectionValue", "constructor", 
		"data", "description", "file", "fileDescription", "fileName", "filePath", 
		"fileSchema", "header", "implementation", "instance", "name", "originating_system", 
		"organization", "parameter", "preprocessor_version", "timeStamp", "value", 
		"viewDefinition", "viewDefinitionType"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "','", "')'", "';'", "'''", "'.'", "'='", "'ViewDefinition'", 
		"'['", "']'", "'CoordinationView'", "'QuantityTakeOffAddOnView'", null, 
		null, null, null, null, "'*'", null, "'ENDSEC'", "'FILE_DESCRIPTION'", 
		"'FILE_NAME'", "'FILE_SCHEMA'", "'HEADER'", null, null, null, null, null, 
		"'$'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "Digit", "Digits", "Letter", "CapitalLetter", "DateTime", "Derived", 
		"EnumBoolLogical", "ENDSEC", "FILE_DESCRIPTION", "FILE_NAME", "FILE_SCHEMA", 
		"HEADER", "Id", "ISO", "ISO_END", "StringLiteral", "TypeRef", "Undefined", 
		"NewlineChar", "WS", "Comments"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "STEP.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static STEPParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public STEPParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public STEPParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class AuthorContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public AuthorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_author; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterAuthor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitAuthor(this);
		}
	}

	[RuleVersion(0)]
	public AuthorContext author() {
		AuthorContext _localctx = new AuthorContext(Context, State);
		EnterRule(_localctx, 0, RULE_author);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AuthorisationContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public AuthorisationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_authorisation; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterAuthorisation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitAuthorisation(this);
		}
	}

	[RuleVersion(0)]
	public AuthorisationContext authorisation() {
		AuthorisationContext _localctx = new AuthorisationContext(Context, State);
		EnterRule(_localctx, 2, RULE_authorisation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionContext : ParserRuleContext {
		public CollectionValueContext[] collectionValue() {
			return GetRuleContexts<CollectionValueContext>();
		}
		public CollectionValueContext collectionValue(int i) {
			return GetRuleContext<CollectionValueContext>(i);
		}
		public CollectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collection; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterCollection(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitCollection(this);
		}
	}

	[RuleVersion(0)]
	public CollectionContext collection() {
		CollectionContext _localctx = new CollectionContext(Context, State);
		EnterRule(_localctx, 4, RULE_collection);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52; Match(T__0);
			State = 53; collectionValue();
			State = 58;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 54; Match(T__1);
				State = 55; collectionValue();
				}
				}
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 61; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionValueContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ITerminalNode Id() { return GetToken(STEPParser.Id, 0); }
		public CollectionValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterCollectionValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitCollectionValue(this);
		}
	}

	[RuleVersion(0)]
	public CollectionValueContext collectionValue() {
		CollectionValueContext _localctx = new CollectionValueContext(Context, State);
		EnterRule(_localctx, 6, RULE_collectionValue);
		try {
			State = 65;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__4:
				EnterOuterAlt(_localctx, 1);
				{
				State = 63; value();
				}
				break;
			case Id:
				EnterOuterAlt(_localctx, 2);
				{
				State = 64; Match(Id);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstructorContext : ParserRuleContext {
		public ITerminalNode TypeRef() { return GetToken(STEPParser.TypeRef, 0); }
		public ParameterContext[] parameter() {
			return GetRuleContexts<ParameterContext>();
		}
		public ParameterContext parameter(int i) {
			return GetRuleContext<ParameterContext>(i);
		}
		public ConstructorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constructor; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterConstructor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitConstructor(this);
		}
	}

	[RuleVersion(0)]
	public ConstructorContext constructor() {
		ConstructorContext _localctx = new ConstructorContext(Context, State);
		EnterRule(_localctx, 8, RULE_constructor);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67; Match(TypeRef);
			State = 68; Match(T__0);
			State = 70;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__4) | (1L << Derived) | (1L << EnumBoolLogical) | (1L << StringLiteral) | (1L << Undefined))) != 0)) {
				{
				State = 69; parameter();
				}
			}

			State = 76;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 72; Match(T__1);
				State = 73; parameter();
				}
				}
				State = 78;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 79; Match(T__2);
			State = 80; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DataContext : ParserRuleContext {
		public InstanceContext[] instance() {
			return GetRuleContexts<InstanceContext>();
		}
		public InstanceContext instance(int i) {
			return GetRuleContext<InstanceContext>(i);
		}
		public DataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_data; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterData(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitData(this);
		}
	}

	[RuleVersion(0)]
	public DataContext data() {
		DataContext _localctx = new DataContext(Context, State);
		EnterRule(_localctx, 10, RULE_data);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Id) {
				{
				{
				State = 82; instance();
				}
				}
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DescriptionContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public DescriptionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_description; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterDescription(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitDescription(this);
		}
	}

	[RuleVersion(0)]
	public DescriptionContext description() {
		DescriptionContext _localctx = new DescriptionContext(Context, State);
		EnterRule(_localctx, 12, RULE_description);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88; Match(T__0);
			State = 89; value();
			State = 90; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileContext : ParserRuleContext {
		public ITerminalNode ISO() { return GetToken(STEPParser.ISO, 0); }
		public HeaderContext header() {
			return GetRuleContext<HeaderContext>(0);
		}
		public DataContext data() {
			return GetRuleContext<DataContext>(0);
		}
		public ITerminalNode ISO_END() { return GetToken(STEPParser.ISO_END, 0); }
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFile(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 14, RULE_file);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92; Match(ISO);
			State = 93; header();
			State = 94; data();
			State = 95; Match(ISO_END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileDescriptionContext : ParserRuleContext {
		public ITerminalNode FILE_DESCRIPTION() { return GetToken(STEPParser.FILE_DESCRIPTION, 0); }
		public DescriptionContext description() {
			return GetRuleContext<DescriptionContext>(0);
		}
		public ImplementationContext implementation() {
			return GetRuleContext<ImplementationContext>(0);
		}
		public FileDescriptionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileDescription; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileDescription(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileDescription(this);
		}
	}

	[RuleVersion(0)]
	public FileDescriptionContext fileDescription() {
		FileDescriptionContext _localctx = new FileDescriptionContext(Context, State);
		EnterRule(_localctx, 16, RULE_fileDescription);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97; Match(FILE_DESCRIPTION);
			State = 98; Match(T__0);
			State = 99; description();
			State = 100; Match(T__1);
			State = 101; implementation();
			State = 102; Match(T__2);
			State = 103; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileNameContext : ParserRuleContext {
		public ITerminalNode FILE_NAME() { return GetToken(STEPParser.FILE_NAME, 0); }
		public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		public TimeStampContext timeStamp() {
			return GetRuleContext<TimeStampContext>(0);
		}
		public AuthorContext author() {
			return GetRuleContext<AuthorContext>(0);
		}
		public OrganizationContext organization() {
			return GetRuleContext<OrganizationContext>(0);
		}
		public Preprocessor_versionContext preprocessor_version() {
			return GetRuleContext<Preprocessor_versionContext>(0);
		}
		public Originating_systemContext originating_system() {
			return GetRuleContext<Originating_systemContext>(0);
		}
		public AuthorisationContext authorisation() {
			return GetRuleContext<AuthorisationContext>(0);
		}
		public FileNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileName(this);
		}
	}

	[RuleVersion(0)]
	public FileNameContext fileName() {
		FileNameContext _localctx = new FileNameContext(Context, State);
		EnterRule(_localctx, 18, RULE_fileName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105; Match(FILE_NAME);
			State = 106; Match(T__0);
			State = 107; name();
			State = 108; Match(T__1);
			State = 109; timeStamp();
			State = 110; Match(T__1);
			State = 111; author();
			State = 112; Match(T__1);
			State = 113; organization();
			State = 114; Match(T__1);
			State = 115; preprocessor_version();
			State = 116; Match(T__1);
			State = 117; originating_system();
			State = 118; Match(T__1);
			State = 119; authorisation();
			State = 120; Match(T__2);
			State = 121; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FilePathContext : ParserRuleContext {
		public ITerminalNode[] Letter() { return GetTokens(STEPParser.Letter); }
		public ITerminalNode Letter(int i) {
			return GetToken(STEPParser.Letter, i);
		}
		public FilePathContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_filePath; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFilePath(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFilePath(this);
		}
	}

	[RuleVersion(0)]
	public FilePathContext filePath() {
		FilePathContext _localctx = new FilePathContext(Context, State);
		EnterRule(_localctx, 20, RULE_filePath);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123; Match(T__4);
			State = 127;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Letter) {
				{
				{
				State = 124; Match(Letter);
				}
				}
				State = 129;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 130; Match(T__5);
			State = 134;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Letter) {
				{
				{
				State = 131; Match(Letter);
				}
				}
				State = 136;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 137; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileSchemaContext : ParserRuleContext {
		public ITerminalNode FILE_SCHEMA() { return GetToken(STEPParser.FILE_SCHEMA, 0); }
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public FileSchemaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileSchema; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileSchema(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileSchema(this);
		}
	}

	[RuleVersion(0)]
	public FileSchemaContext fileSchema() {
		FileSchemaContext _localctx = new FileSchemaContext(Context, State);
		EnterRule(_localctx, 22, RULE_fileSchema);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139; Match(FILE_SCHEMA);
			State = 140; Match(T__0);
			State = 141; Match(T__0);
			State = 142; value();
			State = 143; Match(T__2);
			State = 144; Match(T__2);
			State = 145; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HeaderContext : ParserRuleContext {
		public ITerminalNode HEADER() { return GetToken(STEPParser.HEADER, 0); }
		public FileDescriptionContext fileDescription() {
			return GetRuleContext<FileDescriptionContext>(0);
		}
		public FileNameContext fileName() {
			return GetRuleContext<FileNameContext>(0);
		}
		public FileSchemaContext fileSchema() {
			return GetRuleContext<FileSchemaContext>(0);
		}
		public ITerminalNode ENDSEC() { return GetToken(STEPParser.ENDSEC, 0); }
		public HeaderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_header; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterHeader(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitHeader(this);
		}
	}

	[RuleVersion(0)]
	public HeaderContext header() {
		HeaderContext _localctx = new HeaderContext(Context, State);
		EnterRule(_localctx, 24, RULE_header);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147; Match(HEADER);
			State = 148; Match(T__3);
			State = 149; fileDescription();
			State = 150; fileName();
			State = 151; fileSchema();
			State = 152; Match(ENDSEC);
			State = 153; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImplementationContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ImplementationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_implementation; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterImplementation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitImplementation(this);
		}
	}

	[RuleVersion(0)]
	public ImplementationContext implementation() {
		ImplementationContext _localctx = new ImplementationContext(Context, State);
		EnterRule(_localctx, 26, RULE_implementation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstanceContext : ParserRuleContext {
		public ITerminalNode Id() { return GetToken(STEPParser.Id, 0); }
		public ConstructorContext constructor() {
			return GetRuleContext<ConstructorContext>(0);
		}
		public InstanceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instance; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterInstance(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitInstance(this);
		}
	}

	[RuleVersion(0)]
	public InstanceContext instance() {
		InstanceContext _localctx = new InstanceContext(Context, State);
		EnterRule(_localctx, 28, RULE_instance);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 157; Match(Id);
			State = 158; Match(T__6);
			State = 159; constructor();
			State = 160; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public FilePathContext filePath() {
			return GetRuleContext<FilePathContext>(0);
		}
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitName(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 30, RULE_name);
		try {
			State = 164;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 162; value();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 163; filePath();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Originating_systemContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public Originating_systemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_originating_system; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterOriginating_system(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitOriginating_system(this);
		}
	}

	[RuleVersion(0)]
	public Originating_systemContext originating_system() {
		Originating_systemContext _localctx = new Originating_systemContext(Context, State);
		EnterRule(_localctx, 32, RULE_originating_system);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 166; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrganizationContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public OrganizationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_organization; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterOrganization(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitOrganization(this);
		}
	}

	[RuleVersion(0)]
	public OrganizationContext organization() {
		OrganizationContext _localctx = new OrganizationContext(Context, State);
		EnterRule(_localctx, 34, RULE_organization);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterContext : ParserRuleContext {
		public CollectionContext collection() {
			return GetRuleContext<CollectionContext>(0);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ITerminalNode Undefined() { return GetToken(STEPParser.Undefined, 0); }
		public ITerminalNode StringLiteral() { return GetToken(STEPParser.StringLiteral, 0); }
		public ITerminalNode Derived() { return GetToken(STEPParser.Derived, 0); }
		public ITerminalNode EnumBoolLogical() { return GetToken(STEPParser.EnumBoolLogical, 0); }
		public ParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterParameter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitParameter(this);
		}
	}

	[RuleVersion(0)]
	public ParameterContext parameter() {
		ParameterContext _localctx = new ParameterContext(Context, State);
		EnterRule(_localctx, 36, RULE_parameter);
		try {
			State = 176;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 170; collection();
				}
				break;
			case T__4:
				EnterOuterAlt(_localctx, 2);
				{
				State = 171; value();
				}
				break;
			case Undefined:
				EnterOuterAlt(_localctx, 3);
				{
				State = 172; Match(Undefined);
				}
				break;
			case StringLiteral:
				EnterOuterAlt(_localctx, 4);
				{
				State = 173; Match(StringLiteral);
				}
				break;
			case Derived:
				EnterOuterAlt(_localctx, 5);
				{
				State = 174; Match(Derived);
				}
				break;
			case EnumBoolLogical:
				EnterOuterAlt(_localctx, 6);
				{
				State = 175; Match(EnumBoolLogical);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Preprocessor_versionContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public Preprocessor_versionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_version; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterPreprocessor_version(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitPreprocessor_version(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_versionContext preprocessor_version() {
		Preprocessor_versionContext _localctx = new Preprocessor_versionContext(Context, State);
		EnterRule(_localctx, 38, RULE_preprocessor_version);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 178; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeStampContext : ParserRuleContext {
		public ITerminalNode DateTime() { return GetToken(STEPParser.DateTime, 0); }
		public TimeStampContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeStamp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterTimeStamp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitTimeStamp(this);
		}
	}

	[RuleVersion(0)]
	public TimeStampContext timeStamp() {
		TimeStampContext _localctx = new TimeStampContext(Context, State);
		EnterRule(_localctx, 40, RULE_timeStamp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 180; Match(DateTime);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 42, RULE_value);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 182; Match(T__4);
			State = 186;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 183;
					MatchWildcard();
					}
					} 
				}
				State = 188;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			State = 189; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ViewDefinitionContext : ParserRuleContext {
		public ViewDefinitionTypeContext viewDefinitionType() {
			return GetRuleContext<ViewDefinitionTypeContext>(0);
		}
		public ViewDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_viewDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterViewDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitViewDefinition(this);
		}
	}

	[RuleVersion(0)]
	public ViewDefinitionContext viewDefinition() {
		ViewDefinitionContext _localctx = new ViewDefinitionContext(Context, State);
		EnterRule(_localctx, 44, RULE_viewDefinition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191; Match(T__7);
			State = 192; Match(T__8);
			State = 193; viewDefinitionType();
			State = 194; Match(T__9);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ViewDefinitionTypeContext : ParserRuleContext {
		public ViewDefinitionTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_viewDefinitionType; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterViewDefinitionType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitViewDefinitionType(this);
		}
	}

	[RuleVersion(0)]
	public ViewDefinitionTypeContext viewDefinitionType() {
		ViewDefinitionTypeContext _localctx = new ViewDefinitionTypeContext(Context, State);
		EnterRule(_localctx, 46, RULE_viewDefinitionType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196;
			_la = TokenStream.LA(1);
			if ( !(_la==T__10 || _la==T__11) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '#', '\xC9', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\a', '\x4', ';', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '>', 
		'\v', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x5', 
		'\x5', '\x44', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', 'I', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 
		'M', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 'P', '\v', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\a', '\a', 'V', '\n', 
		'\a', '\f', '\a', '\xE', '\a', 'Y', '\v', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\a', '\f', '\x80', '\n', '\f', '\f', '\f', 
		'\xE', '\f', '\x83', '\v', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', 
		'\x87', '\n', '\f', '\f', '\f', '\xE', '\f', '\x8A', '\v', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x5', '\x11', '\xA7', '\n', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', '\xB3', '\n', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x17', '\x3', '\x17', '\a', '\x17', '\xBB', '\n', '\x17', '\f', '\x17', 
		'\xE', '\x17', '\xBE', '\v', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\xBC', '\x2', '\x1A', '\x2', 
		'\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', 
		'\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', 
		'\x30', '\x2', '\x3', '\x3', '\x2', '\r', '\xE', '\x2', '\xBE', '\x2', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x4', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x6', '\x36', '\x3', '\x2', '\x2', '\x2', '\b', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\n', '\x45', '\x3', '\x2', '\x2', '\x2', '\f', 'W', 
		'\x3', '\x2', '\x2', '\x2', '\xE', 'Z', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'^', '\x3', '\x2', '\x2', '\x2', '\x12', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x14', 'k', '\x3', '\x2', '\x2', '\x2', '\x16', '}', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x9D', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '\x9F', '\x3', '\x2', '\x2', '\x2', ' ', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '\"', '\xA8', '\x3', '\x2', '\x2', '\x2', '$', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '&', '\xB2', '\x3', '\x2', '\x2', '\x2', '(', '\xB4', 
		'\x3', '\x2', '\x2', '\x2', '*', '\xB6', '\x3', '\x2', '\x2', '\x2', ',', 
		'\xB8', '\x3', '\x2', '\x2', '\x2', '.', '\xC1', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\xC6', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\x5', 
		',', '\x17', '\x2', '\x33', '\x3', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x35', '\x5', ',', '\x17', '\x2', '\x35', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x36', '\x37', '\a', '\x3', '\x2', '\x2', '\x37', '<', '\x5', 
		'\b', '\x5', '\x2', '\x38', '\x39', '\a', '\x4', '\x2', '\x2', '\x39', 
		';', '\x5', '\b', '\x5', '\x2', ':', '\x38', '\x3', '\x2', '\x2', '\x2', 
		';', '>', '\x3', '\x2', '\x2', '\x2', '<', ':', '\x3', '\x2', '\x2', '\x2', 
		'<', '=', '\x3', '\x2', '\x2', '\x2', '=', '?', '\x3', '\x2', '\x2', '\x2', 
		'>', '<', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '\x5', '\x2', '\x2', 
		'@', '\a', '\x3', '\x2', '\x2', '\x2', '\x41', '\x44', '\x5', ',', '\x17', 
		'\x2', '\x42', '\x44', '\a', '\x1B', '\x2', '\x2', '\x43', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x42', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\x1F', '\x2', 
		'\x2', '\x46', 'H', '\a', '\x3', '\x2', '\x2', 'G', 'I', '\x5', '&', '\x14', 
		'\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'N', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\a', '\x4', '\x2', 
		'\x2', 'K', 'M', '\x5', '&', '\x14', '\x2', 'L', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'P', '\x3', '\x2', '\x2', '\x2', 'N', 'L', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'O', '\x3', '\x2', '\x2', '\x2', 'O', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'P', 'N', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', '\x5', '\x2', 
		'\x2', 'R', 'S', '\a', '\x6', '\x2', '\x2', 'S', '\v', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'V', '\x5', '\x1E', '\x10', '\x2', 'U', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'Y', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', '\r', '\x3', 
		'\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', 
		'\x3', '\x2', '\x2', '[', '\\', '\x5', ',', '\x17', '\x2', '\\', ']', 
		'\a', '\x5', '\x2', '\x2', ']', '\xF', '\x3', '\x2', '\x2', '\x2', '^', 
		'_', '\a', '\x1C', '\x2', '\x2', '_', '`', '\x5', '\x1A', '\xE', '\x2', 
		'`', '\x61', '\x5', '\f', '\a', '\x2', '\x61', '\x62', '\a', '\x1D', '\x2', 
		'\x2', '\x62', '\x11', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\a', 
		'\x17', '\x2', '\x2', '\x64', '\x65', '\a', '\x3', '\x2', '\x2', '\x65', 
		'\x66', '\x5', '\xE', '\b', '\x2', '\x66', 'g', '\a', '\x4', '\x2', '\x2', 
		'g', 'h', '\x5', '\x1C', '\xF', '\x2', 'h', 'i', '\a', '\x5', '\x2', '\x2', 
		'i', 'j', '\a', '\x6', '\x2', '\x2', 'j', '\x13', '\x3', '\x2', '\x2', 
		'\x2', 'k', 'l', '\a', '\x18', '\x2', '\x2', 'l', 'm', '\a', '\x3', '\x2', 
		'\x2', 'm', 'n', '\x5', ' ', '\x11', '\x2', 'n', 'o', '\a', '\x4', '\x2', 
		'\x2', 'o', 'p', '\x5', '*', '\x16', '\x2', 'p', 'q', '\a', '\x4', '\x2', 
		'\x2', 'q', 'r', '\x5', '\x2', '\x2', '\x2', 'r', 's', '\a', '\x4', '\x2', 
		'\x2', 's', 't', '\x5', '$', '\x13', '\x2', 't', 'u', '\a', '\x4', '\x2', 
		'\x2', 'u', 'v', '\x5', '(', '\x15', '\x2', 'v', 'w', '\a', '\x4', '\x2', 
		'\x2', 'w', 'x', '\x5', '\"', '\x12', '\x2', 'x', 'y', '\a', '\x4', '\x2', 
		'\x2', 'y', 'z', '\x5', '\x4', '\x3', '\x2', 'z', '{', '\a', '\x5', '\x2', 
		'\x2', '{', '|', '\a', '\x6', '\x2', '\x2', '|', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '}', '\x81', '\a', '\a', '\x2', '\x2', '~', '\x80', '\a', 
		'\x11', '\x2', '\x2', '\x7F', '~', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'\x83', '\x3', '\x2', '\x2', '\x2', '\x81', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x81', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x88', '\a', '\b', '\x2', '\x2', '\x85', '\x87', '\a', '\x11', '\x2', 
		'\x2', '\x86', '\x85', '\x3', '\x2', '\x2', '\x2', '\x87', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', 
		'\a', '\x2', '\x2', '\x8C', '\x17', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\a', '\x19', '\x2', '\x2', '\x8E', '\x8F', '\a', '\x3', '\x2', 
		'\x2', '\x8F', '\x90', '\a', '\x3', '\x2', '\x2', '\x90', '\x91', '\x5', 
		',', '\x17', '\x2', '\x91', '\x92', '\a', '\x5', '\x2', '\x2', '\x92', 
		'\x93', '\a', '\x5', '\x2', '\x2', '\x93', '\x94', '\a', '\x6', '\x2', 
		'\x2', '\x94', '\x19', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\a', 
		'\x1A', '\x2', '\x2', '\x96', '\x97', '\a', '\x6', '\x2', '\x2', '\x97', 
		'\x98', '\x5', '\x12', '\n', '\x2', '\x98', '\x99', '\x5', '\x14', '\v', 
		'\x2', '\x99', '\x9A', '\x5', '\x18', '\r', '\x2', '\x9A', '\x9B', '\a', 
		'\x16', '\x2', '\x2', '\x9B', '\x9C', '\a', '\x6', '\x2', '\x2', '\x9C', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x5', ',', '\x17', 
		'\x2', '\x9E', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		'\x1B', '\x2', '\x2', '\xA0', '\xA1', '\a', '\t', '\x2', '\x2', '\xA1', 
		'\xA2', '\x5', '\n', '\x6', '\x2', '\xA2', '\xA3', '\a', '\x6', '\x2', 
		'\x2', '\xA3', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA7', '\x5', 
		',', '\x17', '\x2', '\xA5', '\xA7', '\x5', '\x16', '\f', '\x2', '\xA6', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '!', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x5', 
		',', '\x17', '\x2', '\xA9', '#', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', 
		'\x5', ',', '\x17', '\x2', '\xAB', '%', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xB3', '\x5', '\x6', '\x4', '\x2', '\xAD', '\xB3', '\x5', ',', '\x17', 
		'\x2', '\xAE', '\xB3', '\a', ' ', '\x2', '\x2', '\xAF', '\xB3', '\a', 
		'\x1E', '\x2', '\x2', '\xB0', '\xB3', '\a', '\x14', '\x2', '\x2', '\xB1', 
		'\xB3', '\a', '\x15', '\x2', '\x2', '\xB2', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\'', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\x5', 
		',', '\x17', '\x2', '\xB5', ')', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', 
		'\a', '\x13', '\x2', '\x2', '\xB7', '+', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\xBC', '\a', '\a', '\x2', '\x2', '\xB9', '\xBB', '\v', '\x2', '\x2', 
		'\x2', '\xBA', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xBA', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', 
		'\a', '\x2', '\x2', '\xC0', '-', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', 
		'\a', '\n', '\x2', '\x2', '\xC2', '\xC3', '\a', '\v', '\x2', '\x2', '\xC3', 
		'\xC4', '\x5', '\x30', '\x19', '\x2', '\xC4', '\xC5', '\a', '\f', '\x2', 
		'\x2', '\xC5', '/', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\t', 
		'\x2', '\x2', '\x2', '\xC7', '\x31', '\x3', '\x2', '\x2', '\x2', '\f', 
		'<', '\x43', 'H', 'N', 'W', '\x81', '\x88', '\xA6', '\xB2', '\xBC',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace STEP
