//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from STEP.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace STEP {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class STEPParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, Digit=7, Digits=8, Letter=9, 
		CapitalLetter=10, ENDSEC=11, FILE_DESCRIPTION=12, FILE_NAME=13, FILE_SCHEMA=14, 
		HEADER=15, Id=16, ISO=17, ISO_END=18, StringLiteral=19, TypeRef=20, Undefined=21, 
		NewlineChar=22, WS=23, Comments=24, END_SEC=25;
	public const int
		RULE_author = 0, RULE_authorisation = 1, RULE_collection = 2, RULE_collectionValue = 3, 
		RULE_constructor = 4, RULE_data = 5, RULE_description = 6, RULE_file = 7, 
		RULE_fileDescription = 8, RULE_fileName = 9, RULE_fileSchema = 10, RULE_header = 11, 
		RULE_implementation = 12, RULE_instance = 13, RULE_name = 14, RULE_originating_system = 15, 
		RULE_organization = 16, RULE_parameter = 17, RULE_preprocessor_version = 18, 
		RULE_timeStamp = 19, RULE_value = 20;
	public static readonly string[] ruleNames = {
		"author", "authorisation", "collection", "collectionValue", "constructor", 
		"data", "description", "file", "fileDescription", "fileName", "fileSchema", 
		"header", "implementation", "instance", "name", "originating_system", 
		"organization", "parameter", "preprocessor_version", "timeStamp", "value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "','", "')'", "';'", "'='", "'''", null, null, null, null, 
		"'ENDSEC'", "'FILE_DESCRIPTION'", "'FILE_NAME'", "'FILE_SCHEMA'", "'HEADER'", 
		null, null, null, null, null, "'$'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, "Digit", "Digits", "Letter", 
		"CapitalLetter", "ENDSEC", "FILE_DESCRIPTION", "FILE_NAME", "FILE_SCHEMA", 
		"HEADER", "Id", "ISO", "ISO_END", "StringLiteral", "TypeRef", "Undefined", 
		"NewlineChar", "WS", "Comments", "END_SEC"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "STEP.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static STEPParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public STEPParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public STEPParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class AuthorContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public AuthorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_author; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterAuthor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitAuthor(this);
		}
	}

	[RuleVersion(0)]
	public AuthorContext author() {
		AuthorContext _localctx = new AuthorContext(Context, State);
		EnterRule(_localctx, 0, RULE_author);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AuthorisationContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public AuthorisationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_authorisation; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterAuthorisation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitAuthorisation(this);
		}
	}

	[RuleVersion(0)]
	public AuthorisationContext authorisation() {
		AuthorisationContext _localctx = new AuthorisationContext(Context, State);
		EnterRule(_localctx, 2, RULE_authorisation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionContext : ParserRuleContext {
		public CollectionValueContext[] collectionValue() {
			return GetRuleContexts<CollectionValueContext>();
		}
		public CollectionValueContext collectionValue(int i) {
			return GetRuleContext<CollectionValueContext>(i);
		}
		public CollectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collection; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterCollection(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitCollection(this);
		}
	}

	[RuleVersion(0)]
	public CollectionContext collection() {
		CollectionContext _localctx = new CollectionContext(Context, State);
		EnterRule(_localctx, 4, RULE_collection);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 46; Match(T__0);
			State = 47; collectionValue();
			State = 52;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 48; Match(T__1);
				State = 49; collectionValue();
				}
				}
				State = 54;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 55; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionValueContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ITerminalNode Id() { return GetToken(STEPParser.Id, 0); }
		public CollectionValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterCollectionValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitCollectionValue(this);
		}
	}

	[RuleVersion(0)]
	public CollectionValueContext collectionValue() {
		CollectionValueContext _localctx = new CollectionValueContext(Context, State);
		EnterRule(_localctx, 6, RULE_collectionValue);
		try {
			State = 59;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__5:
				EnterOuterAlt(_localctx, 1);
				{
				State = 57; value();
				}
				break;
			case Id:
				EnterOuterAlt(_localctx, 2);
				{
				State = 58; Match(Id);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstructorContext : ParserRuleContext {
		public ITerminalNode TypeRef() { return GetToken(STEPParser.TypeRef, 0); }
		public ParameterContext[] parameter() {
			return GetRuleContexts<ParameterContext>();
		}
		public ParameterContext parameter(int i) {
			return GetRuleContext<ParameterContext>(i);
		}
		public ConstructorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constructor; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterConstructor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitConstructor(this);
		}
	}

	[RuleVersion(0)]
	public ConstructorContext constructor() {
		ConstructorContext _localctx = new ConstructorContext(Context, State);
		EnterRule(_localctx, 8, RULE_constructor);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61; Match(TypeRef);
			State = 62; Match(T__0);
			State = 64;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__5) | (1L << StringLiteral) | (1L << Undefined))) != 0)) {
				{
				State = 63; parameter();
				}
			}

			State = 70;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 66; Match(T__1);
				State = 67; parameter();
				}
				}
				State = 72;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 73; Match(T__2);
			State = 74; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DataContext : ParserRuleContext {
		public InstanceContext[] instance() {
			return GetRuleContexts<InstanceContext>();
		}
		public InstanceContext instance(int i) {
			return GetRuleContext<InstanceContext>(i);
		}
		public DataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_data; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterData(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitData(this);
		}
	}

	[RuleVersion(0)]
	public DataContext data() {
		DataContext _localctx = new DataContext(Context, State);
		EnterRule(_localctx, 10, RULE_data);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Id) {
				{
				{
				State = 76; instance();
				}
				}
				State = 81;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DescriptionContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public DescriptionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_description; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterDescription(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitDescription(this);
		}
	}

	[RuleVersion(0)]
	public DescriptionContext description() {
		DescriptionContext _localctx = new DescriptionContext(Context, State);
		EnterRule(_localctx, 12, RULE_description);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82; Match(T__0);
			State = 83; value();
			State = 84; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileContext : ParserRuleContext {
		public ITerminalNode ISO() { return GetToken(STEPParser.ISO, 0); }
		public HeaderContext header() {
			return GetRuleContext<HeaderContext>(0);
		}
		public DataContext data() {
			return GetRuleContext<DataContext>(0);
		}
		public ITerminalNode ISO_END() { return GetToken(STEPParser.ISO_END, 0); }
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFile(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 14, RULE_file);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86; Match(ISO);
			State = 87; header();
			State = 88; data();
			State = 89; Match(ISO_END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileDescriptionContext : ParserRuleContext {
		public ITerminalNode FILE_DESCRIPTION() { return GetToken(STEPParser.FILE_DESCRIPTION, 0); }
		public DescriptionContext description() {
			return GetRuleContext<DescriptionContext>(0);
		}
		public ImplementationContext implementation() {
			return GetRuleContext<ImplementationContext>(0);
		}
		public FileDescriptionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileDescription; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileDescription(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileDescription(this);
		}
	}

	[RuleVersion(0)]
	public FileDescriptionContext fileDescription() {
		FileDescriptionContext _localctx = new FileDescriptionContext(Context, State);
		EnterRule(_localctx, 16, RULE_fileDescription);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91; Match(FILE_DESCRIPTION);
			State = 92; Match(T__0);
			State = 93; description();
			State = 94; Match(T__1);
			State = 95; implementation();
			State = 96; Match(T__2);
			State = 97; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileNameContext : ParserRuleContext {
		public ITerminalNode FILE_NAME() { return GetToken(STEPParser.FILE_NAME, 0); }
		public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		public TimeStampContext timeStamp() {
			return GetRuleContext<TimeStampContext>(0);
		}
		public AuthorContext author() {
			return GetRuleContext<AuthorContext>(0);
		}
		public OrganizationContext organization() {
			return GetRuleContext<OrganizationContext>(0);
		}
		public Preprocessor_versionContext preprocessor_version() {
			return GetRuleContext<Preprocessor_versionContext>(0);
		}
		public Originating_systemContext originating_system() {
			return GetRuleContext<Originating_systemContext>(0);
		}
		public AuthorisationContext authorisation() {
			return GetRuleContext<AuthorisationContext>(0);
		}
		public FileNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileName(this);
		}
	}

	[RuleVersion(0)]
	public FileNameContext fileName() {
		FileNameContext _localctx = new FileNameContext(Context, State);
		EnterRule(_localctx, 18, RULE_fileName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99; Match(FILE_NAME);
			State = 100; Match(T__0);
			State = 101; name();
			State = 102; Match(T__1);
			State = 103; timeStamp();
			State = 104; Match(T__1);
			State = 105; author();
			State = 106; Match(T__1);
			State = 107; organization();
			State = 108; Match(T__1);
			State = 109; preprocessor_version();
			State = 110; Match(T__1);
			State = 111; originating_system();
			State = 112; Match(T__1);
			State = 113; authorisation();
			State = 114; Match(T__2);
			State = 115; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileSchemaContext : ParserRuleContext {
		public ITerminalNode FILE_SCHEMA() { return GetToken(STEPParser.FILE_SCHEMA, 0); }
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public FileSchemaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileSchema; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterFileSchema(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitFileSchema(this);
		}
	}

	[RuleVersion(0)]
	public FileSchemaContext fileSchema() {
		FileSchemaContext _localctx = new FileSchemaContext(Context, State);
		EnterRule(_localctx, 20, RULE_fileSchema);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 117; Match(FILE_SCHEMA);
			State = 118; Match(T__0);
			State = 119; Match(T__0);
			State = 120; value();
			State = 121; Match(T__2);
			State = 122; Match(T__2);
			State = 123; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HeaderContext : ParserRuleContext {
		public ITerminalNode HEADER() { return GetToken(STEPParser.HEADER, 0); }
		public FileDescriptionContext fileDescription() {
			return GetRuleContext<FileDescriptionContext>(0);
		}
		public FileNameContext fileName() {
			return GetRuleContext<FileNameContext>(0);
		}
		public FileSchemaContext fileSchema() {
			return GetRuleContext<FileSchemaContext>(0);
		}
		public ITerminalNode END_SEC() { return GetToken(STEPParser.END_SEC, 0); }
		public HeaderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_header; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterHeader(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitHeader(this);
		}
	}

	[RuleVersion(0)]
	public HeaderContext header() {
		HeaderContext _localctx = new HeaderContext(Context, State);
		EnterRule(_localctx, 22, RULE_header);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125; Match(HEADER);
			State = 126; fileDescription();
			State = 127; fileName();
			State = 128; fileSchema();
			State = 129; Match(END_SEC);
			State = 130; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImplementationContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ImplementationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_implementation; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterImplementation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitImplementation(this);
		}
	}

	[RuleVersion(0)]
	public ImplementationContext implementation() {
		ImplementationContext _localctx = new ImplementationContext(Context, State);
		EnterRule(_localctx, 24, RULE_implementation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstanceContext : ParserRuleContext {
		public ITerminalNode Id() { return GetToken(STEPParser.Id, 0); }
		public ConstructorContext constructor() {
			return GetRuleContext<ConstructorContext>(0);
		}
		public InstanceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instance; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterInstance(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitInstance(this);
		}
	}

	[RuleVersion(0)]
	public InstanceContext instance() {
		InstanceContext _localctx = new InstanceContext(Context, State);
		EnterRule(_localctx, 26, RULE_instance);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 134; Match(Id);
			State = 135; Match(T__4);
			State = 136; constructor();
			State = 137; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitName(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 28, RULE_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Originating_systemContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public Originating_systemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_originating_system; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterOriginating_system(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitOriginating_system(this);
		}
	}

	[RuleVersion(0)]
	public Originating_systemContext originating_system() {
		Originating_systemContext _localctx = new Originating_systemContext(Context, State);
		EnterRule(_localctx, 30, RULE_originating_system);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrganizationContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public OrganizationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_organization; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterOrganization(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitOrganization(this);
		}
	}

	[RuleVersion(0)]
	public OrganizationContext organization() {
		OrganizationContext _localctx = new OrganizationContext(Context, State);
		EnterRule(_localctx, 32, RULE_organization);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 143; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterContext : ParserRuleContext {
		public CollectionContext collection() {
			return GetRuleContext<CollectionContext>(0);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ITerminalNode Undefined() { return GetToken(STEPParser.Undefined, 0); }
		public ITerminalNode StringLiteral() { return GetToken(STEPParser.StringLiteral, 0); }
		public ParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterParameter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitParameter(this);
		}
	}

	[RuleVersion(0)]
	public ParameterContext parameter() {
		ParameterContext _localctx = new ParameterContext(Context, State);
		EnterRule(_localctx, 34, RULE_parameter);
		try {
			State = 149;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 145; collection();
				}
				break;
			case T__5:
				EnterOuterAlt(_localctx, 2);
				{
				State = 146; value();
				}
				break;
			case Undefined:
				EnterOuterAlt(_localctx, 3);
				{
				State = 147; Match(Undefined);
				}
				break;
			case StringLiteral:
				EnterOuterAlt(_localctx, 4);
				{
				State = 148; Match(StringLiteral);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Preprocessor_versionContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public Preprocessor_versionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_version; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterPreprocessor_version(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitPreprocessor_version(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_versionContext preprocessor_version() {
		Preprocessor_versionContext _localctx = new Preprocessor_versionContext(Context, State);
		EnterRule(_localctx, 36, RULE_preprocessor_version);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeStampContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public TimeStampContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeStamp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterTimeStamp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitTimeStamp(this);
		}
	}

	[RuleVersion(0)]
	public TimeStampContext timeStamp() {
		TimeStampContext _localctx = new TimeStampContext(Context, State);
		EnterRule(_localctx, 38, RULE_timeStamp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISTEPListener typedListener = listener as ISTEPListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 40, RULE_value);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 155; Match(T__5);
			State = 159;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 156;
					MatchWildcard();
					}
					} 
				}
				State = 161;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			State = 162; Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1B', '\xA7', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 
		'\x35', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x38', '\v', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '>', '\n', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x43', 
		'\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'G', '\n', '\x6', 
		'\f', '\x6', '\xE', '\x6', 'J', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\a', '\a', 'P', '\n', '\a', '\f', '\a', '\xE', 
		'\a', 'S', '\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\x98', 
		'\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\a', '\x16', '\xA0', '\n', '\x16', '\f', 
		'\x16', '\xE', '\x16', '\xA3', '\v', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\xA1', '\x2', '\x17', '\x2', '\x4', '\x6', '\b', 
		'\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', 
		'\x1E', ' ', '\"', '$', '&', '(', '*', '\x2', '\x2', '\x2', '\x9A', '\x2', 
		',', '\x3', '\x2', '\x2', '\x2', '\x4', '.', '\x3', '\x2', '\x2', '\x2', 
		'\x6', '\x30', '\x3', '\x2', '\x2', '\x2', '\b', '=', '\x3', '\x2', '\x2', 
		'\x2', '\n', '?', '\x3', '\x2', '\x2', '\x2', '\f', 'Q', '\x3', '\x2', 
		'\x2', '\x2', '\xE', 'T', '\x3', '\x2', '\x2', '\x2', '\x10', 'X', '\x3', 
		'\x2', '\x2', '\x2', '\x12', ']', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\x16', 'w', '\x3', '\x2', '\x2', 
		'\x2', '\x18', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '\x88', '\x3', '\x2', '\x2', '\x2', '\x1E', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', ' ', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\"', '\x91', '\x3', '\x2', '\x2', '\x2', '$', '\x97', '\x3', '\x2', 
		'\x2', '\x2', '&', '\x99', '\x3', '\x2', '\x2', '\x2', '(', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '*', '\x9D', '\x3', '\x2', '\x2', '\x2', ',', '-', 
		'\x5', '*', '\x16', '\x2', '-', '\x3', '\x3', '\x2', '\x2', '\x2', '.', 
		'/', '\x5', '*', '\x16', '\x2', '/', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x30', '\x31', '\a', '\x3', '\x2', '\x2', '\x31', '\x36', '\x5', '\b', 
		'\x5', '\x2', '\x32', '\x33', '\a', '\x4', '\x2', '\x2', '\x33', '\x35', 
		'\x5', '\b', '\x5', '\x2', '\x34', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x38', '\x3', '\x2', '\x2', '\x2', '\x36', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x36', '\x37', '\x3', '\x2', '\x2', '\x2', '\x37', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x38', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\x39', ':', '\a', '\x5', '\x2', '\x2', ':', '\a', '\x3', '\x2', '\x2', 
		'\x2', ';', '>', '\x5', '*', '\x16', '\x2', '<', '>', '\a', '\x12', '\x2', 
		'\x2', '=', ';', '\x3', '\x2', '\x2', '\x2', '=', '<', '\x3', '\x2', '\x2', 
		'\x2', '>', '\t', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '\x16', 
		'\x2', '\x2', '@', '\x42', '\a', '\x3', '\x2', '\x2', '\x41', '\x43', 
		'\x5', '$', '\x13', '\x2', '\x42', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\x42', '\x43', '\x3', '\x2', '\x2', '\x2', '\x43', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\x44', '\x45', '\a', '\x4', '\x2', '\x2', '\x45', 'G', 
		'\x5', '$', '\x13', '\x2', '\x46', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'G', 'J', '\x3', '\x2', '\x2', '\x2', 'H', '\x46', '\x3', '\x2', '\x2', 
		'\x2', 'H', 'I', '\x3', '\x2', '\x2', '\x2', 'I', 'K', '\x3', '\x2', '\x2', 
		'\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', '\x5', '\x2', 
		'\x2', 'L', 'M', '\a', '\x6', '\x2', '\x2', 'M', '\v', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'P', '\x5', '\x1C', '\xF', '\x2', 'O', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'P', 'S', '\x3', '\x2', '\x2', '\x2', 'Q', 'O', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\x3', '\x2', '\x2', '\x2', 'R', '\r', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', 
		'\x3', '\x2', '\x2', 'U', 'V', '\x5', '*', '\x16', '\x2', 'V', 'W', '\a', 
		'\x5', '\x2', '\x2', 'W', '\xF', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', 
		'\a', '\x13', '\x2', '\x2', 'Y', 'Z', '\x5', '\x18', '\r', '\x2', 'Z', 
		'[', '\x5', '\f', '\a', '\x2', '[', '\\', '\a', '\x14', '\x2', '\x2', 
		'\\', '\x11', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '\xE', '\x2', 
		'\x2', '^', '_', '\a', '\x3', '\x2', '\x2', '_', '`', '\x5', '\xE', '\b', 
		'\x2', '`', '\x61', '\a', '\x4', '\x2', '\x2', '\x61', '\x62', '\x5', 
		'\x1A', '\xE', '\x2', '\x62', '\x63', '\a', '\x5', '\x2', '\x2', '\x63', 
		'\x64', '\a', '\x6', '\x2', '\x2', '\x64', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x66', '\a', '\xF', '\x2', '\x2', '\x66', 'g', '\a', '\x3', 
		'\x2', '\x2', 'g', 'h', '\x5', '\x1E', '\x10', '\x2', 'h', 'i', '\a', 
		'\x4', '\x2', '\x2', 'i', 'j', '\x5', '(', '\x15', '\x2', 'j', 'k', '\a', 
		'\x4', '\x2', '\x2', 'k', 'l', '\x5', '\x2', '\x2', '\x2', 'l', 'm', '\a', 
		'\x4', '\x2', '\x2', 'm', 'n', '\x5', '\"', '\x12', '\x2', 'n', 'o', '\a', 
		'\x4', '\x2', '\x2', 'o', 'p', '\x5', '&', '\x14', '\x2', 'p', 'q', '\a', 
		'\x4', '\x2', '\x2', 'q', 'r', '\x5', ' ', '\x11', '\x2', 'r', 's', '\a', 
		'\x4', '\x2', '\x2', 's', 't', '\x5', '\x4', '\x3', '\x2', 't', 'u', '\a', 
		'\x5', '\x2', '\x2', 'u', 'v', '\a', '\x6', '\x2', '\x2', 'v', '\x15', 
		'\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', '\x10', '\x2', '\x2', 'x', 
		'y', '\a', '\x3', '\x2', '\x2', 'y', 'z', '\a', '\x3', '\x2', '\x2', 'z', 
		'{', '\x5', '*', '\x16', '\x2', '{', '|', '\a', '\x5', '\x2', '\x2', '|', 
		'}', '\a', '\x5', '\x2', '\x2', '}', '~', '\a', '\x6', '\x2', '\x2', '~', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\a', '\x11', '\x2', 
		'\x2', '\x80', '\x81', '\x5', '\x12', '\n', '\x2', '\x81', '\x82', '\x5', 
		'\x14', '\v', '\x2', '\x82', '\x83', '\x5', '\x16', '\f', '\x2', '\x83', 
		'\x84', '\a', '\x1B', '\x2', '\x2', '\x84', '\x85', '\a', '\x6', '\x2', 
		'\x2', '\x85', '\x19', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\x5', 
		'*', '\x16', '\x2', '\x87', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\a', '\x12', '\x2', '\x2', '\x89', '\x8A', '\a', '\a', '\x2', 
		'\x2', '\x8A', '\x8B', '\x5', '\n', '\x6', '\x2', '\x8B', '\x8C', '\a', 
		'\x6', '\x2', '\x2', '\x8C', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\x5', '*', '\x16', '\x2', '\x8E', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\x5', '*', '\x16', '\x2', '\x90', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x92', '\x5', '*', '\x16', '\x2', '\x92', 
		'#', '\x3', '\x2', '\x2', '\x2', '\x93', '\x98', '\x5', '\x6', '\x4', 
		'\x2', '\x94', '\x98', '\x5', '*', '\x16', '\x2', '\x95', '\x98', '\a', 
		'\x17', '\x2', '\x2', '\x96', '\x98', '\a', '\x15', '\x2', '\x2', '\x97', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x97', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\x97', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x96', '\x3', 
		'\x2', '\x2', '\x2', '\x98', '%', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9A', '\x5', '*', '\x16', '\x2', '\x9A', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x9C', '\x5', '*', '\x16', '\x2', '\x9C', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\xA1', '\a', '\b', '\x2', '\x2', '\x9E', 
		'\xA0', '\v', '\x2', '\x2', '\x2', '\x9F', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\xA4', '\xA5', '\a', '\b', '\x2', '\x2', '\xA5', '+', '\x3', '\x2', 
		'\x2', '\x2', '\t', '\x36', '=', '\x42', 'H', 'Q', '\x97', '\xA1',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace STEP
